### ISSUE TITLE
accessibility field in apache-fop-config does not get applied

### ISSUE THREAD

**Issue by MichaelYabko** [cajuncoding/ApacheFOP.Serverless#5]
when setting the pdf rendered mode to PDF/UA-1

![image](https://user-images.githubusercontent.com/59970024/135454868-d1ec4a1c-1e88-4727-9b87-6f9d4727a32b.png)

setting accessibility to true is required to render pdfs, otherwise you'll get the following 500 error with the service:

```
{
  "detailMessage": "PDF/UA-1 requires that the accessibility option in the configuration file be enabled",
  "stackTrace": [],
  "suppressedExceptions": []
}
```

setting it to true in the config file does not seem to work. Current workaround is to include programically here in [ApacheFopRenderer.java](https://github.com/cajuncoding/ApacheFOP.Serverless/blob/0a218fa0b8d78e5acde7c26ca1b130fc2419370c/apachefop-serverless-az-func/src/main/java/com/cajuncoding/apachefop/serverless/apachefop/ApacheFopRenderer.java#L49) 
![image](https://user-images.githubusercontent.com/59970024/135455553-e2c6b61f-e689-4249-aa0f-8ad338cbaa02.png)

**Comment by cajuncoding** [comment]
Interesting... yeah I can confirm that the Xml configuration described here just doesn't work ☹.

So since I was adding a few more details (e.g. Java resource caching for performance), I've now added an Azure Function environment config to control that instead ✅.

So in the Azure Functions env config just add a new configuration value (don't include teh ticks they just denote these are string values, now the code will programatically set the Accessibility enabled state on the FopFactory based on that configuration value (default is false):
```
Key = `AccessibilityEnabled`
Value = `true`
```
